baseURL = "https://diariodeunesclavo.netlify.app/"
languageCode = "es-es"
title = "Diario de un objeto"

[params]
  description = "Vivencias y reflexiones de un esclavo sobre el BDSM y las relaciones D/s."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
