baseURL = "https://diariodeunesclavo.netlify.app/"
languageCode = "es-es"
title = "Diario de un esclavo"

[params]
  description = "vivencias y reflexiones de un esclavo sobre el BDSM y las relaciones D/s."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "diario"
    name = "diario"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "temas"
    name = "temas"
    url = "/tags/"
    weight = 20

  [[menu.main]]
    identifier = "archivo"
    name = "archivo"
    url = "/archivo/"
    weight = 30

  [[menu.main]]
    identifier = "biblioteca"
    name = "biblioteca"
    url = "/biblioteca/"
    weight = 40

  [[menu.main]]
    identifier = "escritos"
    name = "escritos"
    url = "/escritos/"
    weight = 50

  [[menu.main]]
    identifier = "acompanamiento"
    name = "acompañamiento"
    url = "/acompanamiento/"
    weight = 60

  [[menu.main]]
    identifier = "comunidad"
    name = "comunidad"
    url = "/comunidad/"
    weight = 70

  [[menu.main]]
    identifier = "enlaces"
    name = "enlaces"
    url = "/enlaces/"
    weight = 80

  [[menu.main]]
    identifier = "sobre"
    name = "sobre este diario"
    url = "/sobre/"
    weight = 90
